name: Deploy via FTP

on:
  push:
    branches:
      - claude/appointment-booking-calendar-4dCxg

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: w01c3400.kasserver.com
          username: f0180e2d
          password: MN7-=Y3oJAxFHX/bqncP
          server-dir: /
          protocol: ftps
          port: 21
